name: Tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"
      - run: cd module
      - run: npm install
      - run: npm test
